/* tslint:disable */
/* eslint-disable */
/**
 * 通用接口
 * 通用接口，针对权限、通用缓存、调度中心
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { AnalysisEntry } from '../models';
import { RESTfulResultInt32 } from '../models';
import { RESTfulResultListAnalysisEntry } from '../models';
import { RESTfulResultString } from '../models';
/**
 * AnalysisApi - axios parameter creator
 * @export
 */
export const AnalysisApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 删除分析
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAnalysisAnalysisIdDelete: async (id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling apiAnalysisAnalysisIdDelete.');
            }
            const localVarPath = `/api/analysis/analysis/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 建立新分析
         * @param {AnalysisEntry} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAnalysisAnalysisPost: async (body?: AnalysisEntry, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/analysis/analysis`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {AnalysisEntry} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAnalysisAnalysisPut: async (body?: AnalysisEntry, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/analysis/analysis`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 获取所有分析列表
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAnalysisAnalysislistGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/analysis/analysislist`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} analysis 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAnalysisInsfromanalysisAnalysisDelete: async (analysis: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'analysis' is not null or undefined
            if (analysis === null || analysis === undefined) {
                throw new RequiredError('analysis','Required parameter analysis was null or undefined when calling apiAnalysisInsfromanalysisAnalysisDelete.');
            }
            const localVarPath = `/api/analysis/insfromanalysis/{analysis}`
                .replace(`{${"analysis"}}`, encodeURIComponent(String(analysis)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} analysis 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAnalysisInstoanalysisAnalysisPost: async (analysis: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'analysis' is not null or undefined
            if (analysis === null || analysis === undefined) {
                throw new RequiredError('analysis','Required parameter analysis was null or undefined when calling apiAnalysisInstoanalysisAnalysisPost.');
            }
            const localVarPath = `/api/analysis/instoanalysis/{analysis}`
                .replace(`{${"analysis"}}`, encodeURIComponent(String(analysis)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} analysisname 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAnalysisItemfromanalysisAnalysisnameDelete: async (analysisname: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'analysisname' is not null or undefined
            if (analysisname === null || analysisname === undefined) {
                throw new RequiredError('analysisname','Required parameter analysisname was null or undefined when calling apiAnalysisItemfromanalysisAnalysisnameDelete.');
            }
            const localVarPath = `/api/analysis/itemfromanalysis/{analysisname}`
                .replace(`{${"analysisname"}}`, encodeURIComponent(String(analysisname)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} analysisname 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAnalysisItemfromanalysisAnalysisnamePut: async (analysisname: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'analysisname' is not null or undefined
            if (analysisname === null || analysisname === undefined) {
                throw new RequiredError('analysisname','Required parameter analysisname was null or undefined when calling apiAnalysisItemfromanalysisAnalysisnamePut.');
            }
            const localVarPath = `/api/analysis/itemfromanalysis/{analysisname}`
                .replace(`{${"analysisname"}}`, encodeURIComponent(String(analysisname)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} analysisname 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAnalysisItemlistfromanalysisAnalysisnameGet: async (analysisname: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'analysisname' is not null or undefined
            if (analysisname === null || analysisname === undefined) {
                throw new RequiredError('analysisname','Required parameter analysisname was null or undefined when calling apiAnalysisItemlistfromanalysisAnalysisnameGet.');
            }
            const localVarPath = `/api/analysis/itemlistfromanalysis/{analysisname}`
                .replace(`{${"analysisname"}}`, encodeURIComponent(String(analysisname)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} analysisname 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAnalysisItemtoanalysisAnalysisnamePost: async (analysisname: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'analysisname' is not null or undefined
            if (analysisname === null || analysisname === undefined) {
                throw new RequiredError('analysisname','Required parameter analysisname was null or undefined when calling apiAnalysisItemtoanalysisAnalysisnamePost.');
            }
            const localVarPath = `/api/analysis/itemtoanalysis/{analysisname}`
                .replace(`{${"analysisname"}}`, encodeURIComponent(String(analysisname)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} analysis 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAnalysisUserfromanalysisAnalysisDelete: async (analysis: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'analysis' is not null or undefined
            if (analysis === null || analysis === undefined) {
                throw new RequiredError('analysis','Required parameter analysis was null or undefined when calling apiAnalysisUserfromanalysisAnalysisDelete.');
            }
            const localVarPath = `/api/analysis/userfromanalysis/{analysis}`
                .replace(`{${"analysis"}}`, encodeURIComponent(String(analysis)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} analysis 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAnalysisUserlistfromanalysisAnalysisGet: async (analysis: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'analysis' is not null or undefined
            if (analysis === null || analysis === undefined) {
                throw new RequiredError('analysis','Required parameter analysis was null or undefined when calling apiAnalysisUserlistfromanalysisAnalysisGet.');
            }
            const localVarPath = `/api/analysis/userlistfromanalysis/{analysis}`
                .replace(`{${"analysis"}}`, encodeURIComponent(String(analysis)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} analysis 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAnalysisUsertoanalysisAnalysisPost: async (analysis: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'analysis' is not null or undefined
            if (analysis === null || analysis === undefined) {
                throw new RequiredError('analysis','Required parameter analysis was null or undefined when calling apiAnalysisUsertoanalysisAnalysisPost.');
            }
            const localVarPath = `/api/analysis/usertoanalysis/{analysis}`
                .replace(`{${"analysis"}}`, encodeURIComponent(String(analysis)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AnalysisApi - functional programming interface
 * @export
 */
export const AnalysisApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 删除分析
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiAnalysisAnalysisIdDelete(id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<RESTfulResultInt32>>> {
            const localVarAxiosArgs = await AnalysisApiAxiosParamCreator(configuration).apiAnalysisAnalysisIdDelete(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 建立新分析
         * @param {AnalysisEntry} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiAnalysisAnalysisPost(body?: AnalysisEntry, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<RESTfulResultInt32>>> {
            const localVarAxiosArgs = await AnalysisApiAxiosParamCreator(configuration).apiAnalysisAnalysisPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {AnalysisEntry} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiAnalysisAnalysisPut(body?: AnalysisEntry, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<RESTfulResultInt32>>> {
            const localVarAxiosArgs = await AnalysisApiAxiosParamCreator(configuration).apiAnalysisAnalysisPut(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 获取所有分析列表
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiAnalysisAnalysislistGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<RESTfulResultListAnalysisEntry>>> {
            const localVarAxiosArgs = await AnalysisApiAxiosParamCreator(configuration).apiAnalysisAnalysislistGet(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {string} analysis 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiAnalysisInsfromanalysisAnalysisDelete(analysis: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<RESTfulResultString>>> {
            const localVarAxiosArgs = await AnalysisApiAxiosParamCreator(configuration).apiAnalysisInsfromanalysisAnalysisDelete(analysis, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {string} analysis 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiAnalysisInstoanalysisAnalysisPost(analysis: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<RESTfulResultString>>> {
            const localVarAxiosArgs = await AnalysisApiAxiosParamCreator(configuration).apiAnalysisInstoanalysisAnalysisPost(analysis, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {string} analysisname 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiAnalysisItemfromanalysisAnalysisnameDelete(analysisname: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<RESTfulResultString>>> {
            const localVarAxiosArgs = await AnalysisApiAxiosParamCreator(configuration).apiAnalysisItemfromanalysisAnalysisnameDelete(analysisname, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {string} analysisname 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiAnalysisItemfromanalysisAnalysisnamePut(analysisname: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<RESTfulResultString>>> {
            const localVarAxiosArgs = await AnalysisApiAxiosParamCreator(configuration).apiAnalysisItemfromanalysisAnalysisnamePut(analysisname, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {string} analysisname 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiAnalysisItemlistfromanalysisAnalysisnameGet(analysisname: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<RESTfulResultString>>> {
            const localVarAxiosArgs = await AnalysisApiAxiosParamCreator(configuration).apiAnalysisItemlistfromanalysisAnalysisnameGet(analysisname, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {string} analysisname 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiAnalysisItemtoanalysisAnalysisnamePost(analysisname: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<RESTfulResultString>>> {
            const localVarAxiosArgs = await AnalysisApiAxiosParamCreator(configuration).apiAnalysisItemtoanalysisAnalysisnamePost(analysisname, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {string} analysis 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiAnalysisUserfromanalysisAnalysisDelete(analysis: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<RESTfulResultString>>> {
            const localVarAxiosArgs = await AnalysisApiAxiosParamCreator(configuration).apiAnalysisUserfromanalysisAnalysisDelete(analysis, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {string} analysis 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiAnalysisUserlistfromanalysisAnalysisGet(analysis: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<RESTfulResultString>>> {
            const localVarAxiosArgs = await AnalysisApiAxiosParamCreator(configuration).apiAnalysisUserlistfromanalysisAnalysisGet(analysis, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {string} analysis 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiAnalysisUsertoanalysisAnalysisPost(analysis: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<RESTfulResultString>>> {
            const localVarAxiosArgs = await AnalysisApiAxiosParamCreator(configuration).apiAnalysisUsertoanalysisAnalysisPost(analysis, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * AnalysisApi - factory interface
 * @export
 */
export const AnalysisApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary 删除分析
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiAnalysisAnalysisIdDelete(id: number, options?: AxiosRequestConfig): Promise<AxiosResponse<RESTfulResultInt32>> {
            return AnalysisApiFp(configuration).apiAnalysisAnalysisIdDelete(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 建立新分析
         * @param {AnalysisEntry} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiAnalysisAnalysisPost(body?: AnalysisEntry, options?: AxiosRequestConfig): Promise<AxiosResponse<RESTfulResultInt32>> {
            return AnalysisApiFp(configuration).apiAnalysisAnalysisPost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AnalysisEntry} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiAnalysisAnalysisPut(body?: AnalysisEntry, options?: AxiosRequestConfig): Promise<AxiosResponse<RESTfulResultInt32>> {
            return AnalysisApiFp(configuration).apiAnalysisAnalysisPut(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 获取所有分析列表
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiAnalysisAnalysislistGet(options?: AxiosRequestConfig): Promise<AxiosResponse<RESTfulResultListAnalysisEntry>> {
            return AnalysisApiFp(configuration).apiAnalysisAnalysislistGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} analysis 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiAnalysisInsfromanalysisAnalysisDelete(analysis: string, options?: AxiosRequestConfig): Promise<AxiosResponse<RESTfulResultString>> {
            return AnalysisApiFp(configuration).apiAnalysisInsfromanalysisAnalysisDelete(analysis, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} analysis 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiAnalysisInstoanalysisAnalysisPost(analysis: string, options?: AxiosRequestConfig): Promise<AxiosResponse<RESTfulResultString>> {
            return AnalysisApiFp(configuration).apiAnalysisInstoanalysisAnalysisPost(analysis, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} analysisname 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiAnalysisItemfromanalysisAnalysisnameDelete(analysisname: string, options?: AxiosRequestConfig): Promise<AxiosResponse<RESTfulResultString>> {
            return AnalysisApiFp(configuration).apiAnalysisItemfromanalysisAnalysisnameDelete(analysisname, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} analysisname 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiAnalysisItemfromanalysisAnalysisnamePut(analysisname: string, options?: AxiosRequestConfig): Promise<AxiosResponse<RESTfulResultString>> {
            return AnalysisApiFp(configuration).apiAnalysisItemfromanalysisAnalysisnamePut(analysisname, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} analysisname 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiAnalysisItemlistfromanalysisAnalysisnameGet(analysisname: string, options?: AxiosRequestConfig): Promise<AxiosResponse<RESTfulResultString>> {
            return AnalysisApiFp(configuration).apiAnalysisItemlistfromanalysisAnalysisnameGet(analysisname, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} analysisname 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiAnalysisItemtoanalysisAnalysisnamePost(analysisname: string, options?: AxiosRequestConfig): Promise<AxiosResponse<RESTfulResultString>> {
            return AnalysisApiFp(configuration).apiAnalysisItemtoanalysisAnalysisnamePost(analysisname, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} analysis 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiAnalysisUserfromanalysisAnalysisDelete(analysis: string, options?: AxiosRequestConfig): Promise<AxiosResponse<RESTfulResultString>> {
            return AnalysisApiFp(configuration).apiAnalysisUserfromanalysisAnalysisDelete(analysis, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} analysis 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiAnalysisUserlistfromanalysisAnalysisGet(analysis: string, options?: AxiosRequestConfig): Promise<AxiosResponse<RESTfulResultString>> {
            return AnalysisApiFp(configuration).apiAnalysisUserlistfromanalysisAnalysisGet(analysis, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} analysis 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiAnalysisUsertoanalysisAnalysisPost(analysis: string, options?: AxiosRequestConfig): Promise<AxiosResponse<RESTfulResultString>> {
            return AnalysisApiFp(configuration).apiAnalysisUsertoanalysisAnalysisPost(analysis, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AnalysisApi - object-oriented interface
 * @export
 * @class AnalysisApi
 * @extends {BaseAPI}
 */
export class AnalysisApi extends BaseAPI {
    /**
     * 
     * @summary 删除分析
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AnalysisApi
     */
    public async apiAnalysisAnalysisIdDelete(id: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<RESTfulResultInt32>> {
        return AnalysisApiFp(this.configuration).apiAnalysisAnalysisIdDelete(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 建立新分析
     * @param {AnalysisEntry} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AnalysisApi
     */
    public async apiAnalysisAnalysisPost(body?: AnalysisEntry, options?: AxiosRequestConfig) : Promise<AxiosResponse<RESTfulResultInt32>> {
        return AnalysisApiFp(this.configuration).apiAnalysisAnalysisPost(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {AnalysisEntry} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AnalysisApi
     */
    public async apiAnalysisAnalysisPut(body?: AnalysisEntry, options?: AxiosRequestConfig) : Promise<AxiosResponse<RESTfulResultInt32>> {
        return AnalysisApiFp(this.configuration).apiAnalysisAnalysisPut(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 获取所有分析列表
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AnalysisApi
     */
    public async apiAnalysisAnalysislistGet(options?: AxiosRequestConfig) : Promise<AxiosResponse<RESTfulResultListAnalysisEntry>> {
        return AnalysisApiFp(this.configuration).apiAnalysisAnalysislistGet(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {string} analysis 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AnalysisApi
     */
    public async apiAnalysisInsfromanalysisAnalysisDelete(analysis: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<RESTfulResultString>> {
        return AnalysisApiFp(this.configuration).apiAnalysisInsfromanalysisAnalysisDelete(analysis, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {string} analysis 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AnalysisApi
     */
    public async apiAnalysisInstoanalysisAnalysisPost(analysis: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<RESTfulResultString>> {
        return AnalysisApiFp(this.configuration).apiAnalysisInstoanalysisAnalysisPost(analysis, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {string} analysisname 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AnalysisApi
     */
    public async apiAnalysisItemfromanalysisAnalysisnameDelete(analysisname: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<RESTfulResultString>> {
        return AnalysisApiFp(this.configuration).apiAnalysisItemfromanalysisAnalysisnameDelete(analysisname, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {string} analysisname 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AnalysisApi
     */
    public async apiAnalysisItemfromanalysisAnalysisnamePut(analysisname: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<RESTfulResultString>> {
        return AnalysisApiFp(this.configuration).apiAnalysisItemfromanalysisAnalysisnamePut(analysisname, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {string} analysisname 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AnalysisApi
     */
    public async apiAnalysisItemlistfromanalysisAnalysisnameGet(analysisname: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<RESTfulResultString>> {
        return AnalysisApiFp(this.configuration).apiAnalysisItemlistfromanalysisAnalysisnameGet(analysisname, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {string} analysisname 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AnalysisApi
     */
    public async apiAnalysisItemtoanalysisAnalysisnamePost(analysisname: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<RESTfulResultString>> {
        return AnalysisApiFp(this.configuration).apiAnalysisItemtoanalysisAnalysisnamePost(analysisname, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {string} analysis 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AnalysisApi
     */
    public async apiAnalysisUserfromanalysisAnalysisDelete(analysis: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<RESTfulResultString>> {
        return AnalysisApiFp(this.configuration).apiAnalysisUserfromanalysisAnalysisDelete(analysis, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {string} analysis 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AnalysisApi
     */
    public async apiAnalysisUserlistfromanalysisAnalysisGet(analysis: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<RESTfulResultString>> {
        return AnalysisApiFp(this.configuration).apiAnalysisUserlistfromanalysisAnalysisGet(analysis, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {string} analysis 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AnalysisApi
     */
    public async apiAnalysisUsertoanalysisAnalysisPost(analysis: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<RESTfulResultString>> {
        return AnalysisApiFp(this.configuration).apiAnalysisUsertoanalysisAnalysisPost(analysis, options).then((request) => request(this.axios, this.basePath));
    }
}
