/* tslint:disable */
/* eslint-disable */
/**
 * 通用接口
 * 通用接口，针对权限、通用缓存、调度中心
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { RESTfulResultString } from '../models';
/**
 * SampleApi - axios parameter creator
 * @export
 */
export const SampleApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} sampleNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSampleActivesampleSampleNumberPost: async (sampleNumber: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'sampleNumber' is not null or undefined
            if (sampleNumber === null || sampleNumber === undefined) {
                throw new RequiredError('sampleNumber','Required parameter sampleNumber was null or undefined when calling apiSampleActivesampleSampleNumberPost.');
            }
            const localVarPath = `/api/sample/activesample/{sample_number}`
                .replace(`{${"sample_number"}}`, encodeURIComponent(String(sampleNumber)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} sampleNumber 
         * @param {string} auditgrade 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSampleAuditsampleSampleNumberAuditgradePost: async (sampleNumber: string, auditgrade: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'sampleNumber' is not null or undefined
            if (sampleNumber === null || sampleNumber === undefined) {
                throw new RequiredError('sampleNumber','Required parameter sampleNumber was null or undefined when calling apiSampleAuditsampleSampleNumberAuditgradePost.');
            }
            // verify required parameter 'auditgrade' is not null or undefined
            if (auditgrade === null || auditgrade === undefined) {
                throw new RequiredError('auditgrade','Required parameter auditgrade was null or undefined when calling apiSampleAuditsampleSampleNumberAuditgradePost.');
            }
            const localVarPath = `/api/sample/auditsample/{sample_number}/{auditgrade}`
                .replace(`{${"sample_number"}}`, encodeURIComponent(String(sampleNumber)))
                .replace(`{${"auditgrade"}}`, encodeURIComponent(String(auditgrade)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 登记样品
         * @param {string} sampleNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSampleLoginsampleSampleNumberPost: async (sampleNumber: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'sampleNumber' is not null or undefined
            if (sampleNumber === null || sampleNumber === undefined) {
                throw new RequiredError('sampleNumber','Required parameter sampleNumber was null or undefined when calling apiSampleLoginsampleSampleNumberPost.');
            }
            const localVarPath = `/api/sample/loginsample/{sample_number}`
                .replace(`{${"sample_number"}}`, encodeURIComponent(String(sampleNumber)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} sampleNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSamplePackagesampleSampleNumberPost: async (sampleNumber: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'sampleNumber' is not null or undefined
            if (sampleNumber === null || sampleNumber === undefined) {
                throw new RequiredError('sampleNumber','Required parameter sampleNumber was null or undefined when calling apiSamplePackagesampleSampleNumberPost.');
            }
            const localVarPath = `/api/sample/packagesample/{sample_number}`
                .replace(`{${"sample_number"}}`, encodeURIComponent(String(sampleNumber)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} sampleNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSampleReceivesampleSampleNumberPost: async (sampleNumber: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'sampleNumber' is not null or undefined
            if (sampleNumber === null || sampleNumber === undefined) {
                throw new RequiredError('sampleNumber','Required parameter sampleNumber was null or undefined when calling apiSampleReceivesampleSampleNumberPost.');
            }
            const localVarPath = `/api/sample/receivesample/{sample_number}`
                .replace(`{${"sample_number"}}`, encodeURIComponent(String(sampleNumber)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} sampleNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSampleRejectsampleSampleNumberPost: async (sampleNumber: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'sampleNumber' is not null or undefined
            if (sampleNumber === null || sampleNumber === undefined) {
                throw new RequiredError('sampleNumber','Required parameter sampleNumber was null or undefined when calling apiSampleRejectsampleSampleNumberPost.');
            }
            const localVarPath = `/api/sample/rejectsample/{sample_number}`
                .replace(`{${"sample_number"}}`, encodeURIComponent(String(sampleNumber)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} sampleNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSampleRetainsampleSampleNumberPost: async (sampleNumber: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'sampleNumber' is not null or undefined
            if (sampleNumber === null || sampleNumber === undefined) {
                throw new RequiredError('sampleNumber','Required parameter sampleNumber was null or undefined when calling apiSampleRetainsampleSampleNumberPost.');
            }
            const localVarPath = `/api/sample/retainsample/{sample_number}`
                .replace(`{${"sample_number"}}`, encodeURIComponent(String(sampleNumber)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} sampleNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSampleSampleSampleNumberPut: async (sampleNumber: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'sampleNumber' is not null or undefined
            if (sampleNumber === null || sampleNumber === undefined) {
                throw new RequiredError('sampleNumber','Required parameter sampleNumber was null or undefined when calling apiSampleSampleSampleNumberPut.');
            }
            const localVarPath = `/api/sample/sample/{sample_number}`
                .replace(`{${"sample_number"}}`, encodeURIComponent(String(sampleNumber)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} sampleNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSampleSamplestatusSampleNumberPut: async (sampleNumber: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'sampleNumber' is not null or undefined
            if (sampleNumber === null || sampleNumber === undefined) {
                throw new RequiredError('sampleNumber','Required parameter sampleNumber was null or undefined when calling apiSampleSamplestatusSampleNumberPut.');
            }
            const localVarPath = `/api/sample/samplestatus/{sample_number}`
                .replace(`{${"sample_number"}}`, encodeURIComponent(String(sampleNumber)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} sampleNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSampleTestfromsampleSampleNumberDelete: async (sampleNumber: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'sampleNumber' is not null or undefined
            if (sampleNumber === null || sampleNumber === undefined) {
                throw new RequiredError('sampleNumber','Required parameter sampleNumber was null or undefined when calling apiSampleTestfromsampleSampleNumberDelete.');
            }
            const localVarPath = `/api/sample/testfromsample/{sample_number}`
                .replace(`{${"sample_number"}}`, encodeURIComponent(String(sampleNumber)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} sampleNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSampleTesttosampleSampleNumberPost: async (sampleNumber: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'sampleNumber' is not null or undefined
            if (sampleNumber === null || sampleNumber === undefined) {
                throw new RequiredError('sampleNumber','Required parameter sampleNumber was null or undefined when calling apiSampleTesttosampleSampleNumberPost.');
            }
            const localVarPath = `/api/sample/testtosample/{sample_number}`
                .replace(`{${"sample_number"}}`, encodeURIComponent(String(sampleNumber)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SampleApi - functional programming interface
 * @export
 */
export const SampleApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} sampleNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSampleActivesampleSampleNumberPost(sampleNumber: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<RESTfulResultString>>> {
            const localVarAxiosArgs = await SampleApiAxiosParamCreator(configuration).apiSampleActivesampleSampleNumberPost(sampleNumber, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {string} sampleNumber 
         * @param {string} auditgrade 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSampleAuditsampleSampleNumberAuditgradePost(sampleNumber: string, auditgrade: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<RESTfulResultString>>> {
            const localVarAxiosArgs = await SampleApiAxiosParamCreator(configuration).apiSampleAuditsampleSampleNumberAuditgradePost(sampleNumber, auditgrade, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 登记样品
         * @param {string} sampleNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSampleLoginsampleSampleNumberPost(sampleNumber: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<RESTfulResultString>>> {
            const localVarAxiosArgs = await SampleApiAxiosParamCreator(configuration).apiSampleLoginsampleSampleNumberPost(sampleNumber, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {string} sampleNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSamplePackagesampleSampleNumberPost(sampleNumber: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<RESTfulResultString>>> {
            const localVarAxiosArgs = await SampleApiAxiosParamCreator(configuration).apiSamplePackagesampleSampleNumberPost(sampleNumber, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {string} sampleNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSampleReceivesampleSampleNumberPost(sampleNumber: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<RESTfulResultString>>> {
            const localVarAxiosArgs = await SampleApiAxiosParamCreator(configuration).apiSampleReceivesampleSampleNumberPost(sampleNumber, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {string} sampleNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSampleRejectsampleSampleNumberPost(sampleNumber: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<RESTfulResultString>>> {
            const localVarAxiosArgs = await SampleApiAxiosParamCreator(configuration).apiSampleRejectsampleSampleNumberPost(sampleNumber, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {string} sampleNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSampleRetainsampleSampleNumberPost(sampleNumber: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<RESTfulResultString>>> {
            const localVarAxiosArgs = await SampleApiAxiosParamCreator(configuration).apiSampleRetainsampleSampleNumberPost(sampleNumber, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {string} sampleNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSampleSampleSampleNumberPut(sampleNumber: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<RESTfulResultString>>> {
            const localVarAxiosArgs = await SampleApiAxiosParamCreator(configuration).apiSampleSampleSampleNumberPut(sampleNumber, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {string} sampleNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSampleSamplestatusSampleNumberPut(sampleNumber: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<RESTfulResultString>>> {
            const localVarAxiosArgs = await SampleApiAxiosParamCreator(configuration).apiSampleSamplestatusSampleNumberPut(sampleNumber, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {string} sampleNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSampleTestfromsampleSampleNumberDelete(sampleNumber: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<RESTfulResultString>>> {
            const localVarAxiosArgs = await SampleApiAxiosParamCreator(configuration).apiSampleTestfromsampleSampleNumberDelete(sampleNumber, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {string} sampleNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSampleTesttosampleSampleNumberPost(sampleNumber: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<RESTfulResultString>>> {
            const localVarAxiosArgs = await SampleApiAxiosParamCreator(configuration).apiSampleTesttosampleSampleNumberPost(sampleNumber, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * SampleApi - factory interface
 * @export
 */
export const SampleApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {string} sampleNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSampleActivesampleSampleNumberPost(sampleNumber: string, options?: AxiosRequestConfig): Promise<AxiosResponse<RESTfulResultString>> {
            return SampleApiFp(configuration).apiSampleActivesampleSampleNumberPost(sampleNumber, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} sampleNumber 
         * @param {string} auditgrade 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSampleAuditsampleSampleNumberAuditgradePost(sampleNumber: string, auditgrade: string, options?: AxiosRequestConfig): Promise<AxiosResponse<RESTfulResultString>> {
            return SampleApiFp(configuration).apiSampleAuditsampleSampleNumberAuditgradePost(sampleNumber, auditgrade, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 登记样品
         * @param {string} sampleNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSampleLoginsampleSampleNumberPost(sampleNumber: string, options?: AxiosRequestConfig): Promise<AxiosResponse<RESTfulResultString>> {
            return SampleApiFp(configuration).apiSampleLoginsampleSampleNumberPost(sampleNumber, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} sampleNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSamplePackagesampleSampleNumberPost(sampleNumber: string, options?: AxiosRequestConfig): Promise<AxiosResponse<RESTfulResultString>> {
            return SampleApiFp(configuration).apiSamplePackagesampleSampleNumberPost(sampleNumber, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} sampleNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSampleReceivesampleSampleNumberPost(sampleNumber: string, options?: AxiosRequestConfig): Promise<AxiosResponse<RESTfulResultString>> {
            return SampleApiFp(configuration).apiSampleReceivesampleSampleNumberPost(sampleNumber, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} sampleNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSampleRejectsampleSampleNumberPost(sampleNumber: string, options?: AxiosRequestConfig): Promise<AxiosResponse<RESTfulResultString>> {
            return SampleApiFp(configuration).apiSampleRejectsampleSampleNumberPost(sampleNumber, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} sampleNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSampleRetainsampleSampleNumberPost(sampleNumber: string, options?: AxiosRequestConfig): Promise<AxiosResponse<RESTfulResultString>> {
            return SampleApiFp(configuration).apiSampleRetainsampleSampleNumberPost(sampleNumber, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} sampleNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSampleSampleSampleNumberPut(sampleNumber: string, options?: AxiosRequestConfig): Promise<AxiosResponse<RESTfulResultString>> {
            return SampleApiFp(configuration).apiSampleSampleSampleNumberPut(sampleNumber, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} sampleNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSampleSamplestatusSampleNumberPut(sampleNumber: string, options?: AxiosRequestConfig): Promise<AxiosResponse<RESTfulResultString>> {
            return SampleApiFp(configuration).apiSampleSamplestatusSampleNumberPut(sampleNumber, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} sampleNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSampleTestfromsampleSampleNumberDelete(sampleNumber: string, options?: AxiosRequestConfig): Promise<AxiosResponse<RESTfulResultString>> {
            return SampleApiFp(configuration).apiSampleTestfromsampleSampleNumberDelete(sampleNumber, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} sampleNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSampleTesttosampleSampleNumberPost(sampleNumber: string, options?: AxiosRequestConfig): Promise<AxiosResponse<RESTfulResultString>> {
            return SampleApiFp(configuration).apiSampleTesttosampleSampleNumberPost(sampleNumber, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SampleApi - object-oriented interface
 * @export
 * @class SampleApi
 * @extends {BaseAPI}
 */
export class SampleApi extends BaseAPI {
    /**
     * 
     * @param {string} sampleNumber 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SampleApi
     */
    public async apiSampleActivesampleSampleNumberPost(sampleNumber: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<RESTfulResultString>> {
        return SampleApiFp(this.configuration).apiSampleActivesampleSampleNumberPost(sampleNumber, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {string} sampleNumber 
     * @param {string} auditgrade 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SampleApi
     */
    public async apiSampleAuditsampleSampleNumberAuditgradePost(sampleNumber: string, auditgrade: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<RESTfulResultString>> {
        return SampleApiFp(this.configuration).apiSampleAuditsampleSampleNumberAuditgradePost(sampleNumber, auditgrade, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 登记样品
     * @param {string} sampleNumber 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SampleApi
     */
    public async apiSampleLoginsampleSampleNumberPost(sampleNumber: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<RESTfulResultString>> {
        return SampleApiFp(this.configuration).apiSampleLoginsampleSampleNumberPost(sampleNumber, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {string} sampleNumber 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SampleApi
     */
    public async apiSamplePackagesampleSampleNumberPost(sampleNumber: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<RESTfulResultString>> {
        return SampleApiFp(this.configuration).apiSamplePackagesampleSampleNumberPost(sampleNumber, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {string} sampleNumber 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SampleApi
     */
    public async apiSampleReceivesampleSampleNumberPost(sampleNumber: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<RESTfulResultString>> {
        return SampleApiFp(this.configuration).apiSampleReceivesampleSampleNumberPost(sampleNumber, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {string} sampleNumber 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SampleApi
     */
    public async apiSampleRejectsampleSampleNumberPost(sampleNumber: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<RESTfulResultString>> {
        return SampleApiFp(this.configuration).apiSampleRejectsampleSampleNumberPost(sampleNumber, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {string} sampleNumber 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SampleApi
     */
    public async apiSampleRetainsampleSampleNumberPost(sampleNumber: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<RESTfulResultString>> {
        return SampleApiFp(this.configuration).apiSampleRetainsampleSampleNumberPost(sampleNumber, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {string} sampleNumber 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SampleApi
     */
    public async apiSampleSampleSampleNumberPut(sampleNumber: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<RESTfulResultString>> {
        return SampleApiFp(this.configuration).apiSampleSampleSampleNumberPut(sampleNumber, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {string} sampleNumber 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SampleApi
     */
    public async apiSampleSamplestatusSampleNumberPut(sampleNumber: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<RESTfulResultString>> {
        return SampleApiFp(this.configuration).apiSampleSamplestatusSampleNumberPut(sampleNumber, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {string} sampleNumber 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SampleApi
     */
    public async apiSampleTestfromsampleSampleNumberDelete(sampleNumber: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<RESTfulResultString>> {
        return SampleApiFp(this.configuration).apiSampleTestfromsampleSampleNumberDelete(sampleNumber, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {string} sampleNumber 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SampleApi
     */
    public async apiSampleTesttosampleSampleNumberPost(sampleNumber: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<RESTfulResultString>> {
        return SampleApiFp(this.configuration).apiSampleTesttosampleSampleNumberPost(sampleNumber, options).then((request) => request(this.axios, this.basePath));
    }
}
