/* tslint:disable */
/* eslint-disable */
/**
 * 通用接口
 * 通用接口，针对权限、通用缓存、调度中心
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { RESTfulResultPageOutEntity } from '../models';
import { RESTfulResultString } from '../models';
import { SysUserEntry } from '../models';
/**
 * SysuserApi - axios parameter creator
 * @export
 */
export const SysuserApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 添加用户
         * @param {SysUserEntry} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSysuserUserPost: async (body?: SysUserEntry, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/sysuser/user`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 更新用户信息
         * @param {SysUserEntry} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSysuserUserPut: async (body?: SysUserEntry, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/sysuser/user`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 获取用户列表
         * @param {string} [userId] 
         * @param {string} [userName] 
         * @param {string} [userGroup] 
         * @param {string} [userType] 
         * @param {string} [avatar] 
         * @param {string} [lastLoginIp] 
         * @param {Date} [lastLoginTime] 
         * @param {string} [status] 
         * @param {number} [pageIndex] 当前页码
         * @param {number} [pageSize] 每页数据数
         * @param {number} [total] 数据总数
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSysuserUserlistGet: async (userId?: string, userName?: string, userGroup?: string, userType?: string, avatar?: string, lastLoginIp?: string, lastLoginTime?: Date, status?: string, pageIndex?: number, pageSize?: number, total?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/sysuser/userlist`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (userId !== undefined) {
                localVarQueryParameter['UserId'] = userId;
            }

            if (userName !== undefined) {
                localVarQueryParameter['UserName'] = userName;
            }

            if (userGroup !== undefined) {
                localVarQueryParameter['UserGroup'] = userGroup;
            }

            if (userType !== undefined) {
                localVarQueryParameter['UserType'] = userType;
            }

            if (avatar !== undefined) {
                localVarQueryParameter['Avatar'] = avatar;
            }

            if (lastLoginIp !== undefined) {
                localVarQueryParameter['LastLoginIp'] = lastLoginIp;
            }

            if (lastLoginTime !== undefined) {
                localVarQueryParameter['LastLoginTime'] = (lastLoginTime as any instanceof Date) ?
                    (lastLoginTime as any).toISOString() :
                    lastLoginTime;
            }

            if (status !== undefined) {
                localVarQueryParameter['Status'] = status;
            }

            if (pageIndex !== undefined) {
                localVarQueryParameter['PageIndex'] = pageIndex;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['PageSize'] = pageSize;
            }

            if (total !== undefined) {
                localVarQueryParameter['total'] = total;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SysuserApi - functional programming interface
 * @export
 */
export const SysuserApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 添加用户
         * @param {SysUserEntry} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSysuserUserPost(body?: SysUserEntry, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<RESTfulResultString>>> {
            const localVarAxiosArgs = await SysuserApiAxiosParamCreator(configuration).apiSysuserUserPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 更新用户信息
         * @param {SysUserEntry} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSysuserUserPut(body?: SysUserEntry, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<RESTfulResultString>>> {
            const localVarAxiosArgs = await SysuserApiAxiosParamCreator(configuration).apiSysuserUserPut(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 获取用户列表
         * @param {string} [userId] 
         * @param {string} [userName] 
         * @param {string} [userGroup] 
         * @param {string} [userType] 
         * @param {string} [avatar] 
         * @param {string} [lastLoginIp] 
         * @param {Date} [lastLoginTime] 
         * @param {string} [status] 
         * @param {number} [pageIndex] 当前页码
         * @param {number} [pageSize] 每页数据数
         * @param {number} [total] 数据总数
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSysuserUserlistGet(userId?: string, userName?: string, userGroup?: string, userType?: string, avatar?: string, lastLoginIp?: string, lastLoginTime?: Date, status?: string, pageIndex?: number, pageSize?: number, total?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<RESTfulResultPageOutEntity>>> {
            const localVarAxiosArgs = await SysuserApiAxiosParamCreator(configuration).apiSysuserUserlistGet(userId, userName, userGroup, userType, avatar, lastLoginIp, lastLoginTime, status, pageIndex, pageSize, total, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * SysuserApi - factory interface
 * @export
 */
export const SysuserApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary 添加用户
         * @param {SysUserEntry} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSysuserUserPost(body?: SysUserEntry, options?: AxiosRequestConfig): Promise<AxiosResponse<RESTfulResultString>> {
            return SysuserApiFp(configuration).apiSysuserUserPost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 更新用户信息
         * @param {SysUserEntry} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSysuserUserPut(body?: SysUserEntry, options?: AxiosRequestConfig): Promise<AxiosResponse<RESTfulResultString>> {
            return SysuserApiFp(configuration).apiSysuserUserPut(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 获取用户列表
         * @param {string} [userId] 
         * @param {string} [userName] 
         * @param {string} [userGroup] 
         * @param {string} [userType] 
         * @param {string} [avatar] 
         * @param {string} [lastLoginIp] 
         * @param {Date} [lastLoginTime] 
         * @param {string} [status] 
         * @param {number} [pageIndex] 当前页码
         * @param {number} [pageSize] 每页数据数
         * @param {number} [total] 数据总数
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSysuserUserlistGet(userId?: string, userName?: string, userGroup?: string, userType?: string, avatar?: string, lastLoginIp?: string, lastLoginTime?: Date, status?: string, pageIndex?: number, pageSize?: number, total?: number, options?: AxiosRequestConfig): Promise<AxiosResponse<RESTfulResultPageOutEntity>> {
            return SysuserApiFp(configuration).apiSysuserUserlistGet(userId, userName, userGroup, userType, avatar, lastLoginIp, lastLoginTime, status, pageIndex, pageSize, total, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SysuserApi - object-oriented interface
 * @export
 * @class SysuserApi
 * @extends {BaseAPI}
 */
export class SysuserApi extends BaseAPI {
    /**
     * 
     * @summary 添加用户
     * @param {SysUserEntry} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SysuserApi
     */
    public async apiSysuserUserPost(body?: SysUserEntry, options?: AxiosRequestConfig) : Promise<AxiosResponse<RESTfulResultString>> {
        return SysuserApiFp(this.configuration).apiSysuserUserPost(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 更新用户信息
     * @param {SysUserEntry} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SysuserApi
     */
    public async apiSysuserUserPut(body?: SysUserEntry, options?: AxiosRequestConfig) : Promise<AxiosResponse<RESTfulResultString>> {
        return SysuserApiFp(this.configuration).apiSysuserUserPut(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 获取用户列表
     * @param {string} [userId] 
     * @param {string} [userName] 
     * @param {string} [userGroup] 
     * @param {string} [userType] 
     * @param {string} [avatar] 
     * @param {string} [lastLoginIp] 
     * @param {Date} [lastLoginTime] 
     * @param {string} [status] 
     * @param {number} [pageIndex] 当前页码
     * @param {number} [pageSize] 每页数据数
     * @param {number} [total] 数据总数
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SysuserApi
     */
    public async apiSysuserUserlistGet(userId?: string, userName?: string, userGroup?: string, userType?: string, avatar?: string, lastLoginIp?: string, lastLoginTime?: Date, status?: string, pageIndex?: number, pageSize?: number, total?: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<RESTfulResultPageOutEntity>> {
        return SysuserApiFp(this.configuration).apiSysuserUserlistGet(userId, userName, userGroup, userType, avatar, lastLoginIp, lastLoginTime, status, pageIndex, pageSize, total, options).then((request) => request(this.axios, this.basePath));
    }
}
