/* tslint:disable */
/* eslint-disable */
/**
 * 通用接口
 * 通用接口，针对权限、通用缓存、调度中心
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 列表管理，等同于字典管理
 *
 * @export
 * @interface LimsListEntry
 */
export interface LimsListEntry {

    /**
     * @type {string}
     * @memberof LimsListEntry
     */
    createUser?: string | null;

    /**
     * @type {Date}
     * @memberof LimsListEntry
     */
    createTime?: Date | null;

    /**
     * @type {string}
     * @memberof LimsListEntry
     */
    changeUser?: string | null;

    /**
     * @type {Date}
     * @memberof LimsListEntry
     */
    changeTime?: Date | null;

    /**
     * 0为未删除，1为已删除
     *
     * @type {string}
     * @memberof LimsListEntry
     */
    deleted?: string | null;

    /**
     * 数据权限
     *
     * @type {string}
     * @memberof LimsListEntry
     */
    dataId?: string | null;

    /**
     * 主键
     *
     * @type {number}
     * @memberof LimsListEntry
     */
    id?: number;

    /**
     * 列表名称
     *
     * @type {string}
     * @memberof LimsListEntry
     */
    name?: string | null;

    /**
     * 列表描述
     *
     * @type {string}
     * @memberof LimsListEntry
     */
    description?: string | null;

    /**
     * 列表分类
     *
     * @type {string}
     * @memberof LimsListEntry
     */
    listType?: string | null;

    /**
     * 组名
     *
     * @type {string}
     * @memberof LimsListEntry
     */
    groupName?: string | null;
}
