/* tslint:disable */
/* eslint-disable */
/**
 * 通用接口
 * 通用接口，针对权限、通用缓存、调度中心
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 产品实体类
 *
 * @export
 * @interface ProductEntry
 */
export interface ProductEntry {

    /**
     * @type {string}
     * @memberof ProductEntry
     */
    createUser?: string | null;

    /**
     * @type {Date}
     * @memberof ProductEntry
     */
    createTime?: Date | null;

    /**
     * @type {string}
     * @memberof ProductEntry
     */
    changeUser?: string | null;

    /**
     * @type {Date}
     * @memberof ProductEntry
     */
    changeTime?: Date | null;

    /**
     * 0为未删除，1为已删除
     *
     * @type {string}
     * @memberof ProductEntry
     */
    deleted?: string | null;

    /**
     * 数据权限
     *
     * @type {string}
     * @memberof ProductEntry
     */
    dataId?: string | null;

    /**
     * 自增主键
     *
     * @type {number}
     * @memberof ProductEntry
     */
    id?: number;

    /**
     * 产品名称
     *
     * @type {string}
     * @memberof ProductEntry
     */
    name?: string | null;

    /**
     * 别名
     *
     * @type {string}
     * @memberof ProductEntry
     */
    aliasName?: string | null;

    /**
     * 产品代码
     *
     * @type {string}
     * @memberof ProductEntry
     */
    code?: string | null;

    /**
     * 检测单名称
     *
     * @type {string}
     * @memberof ProductEntry
     */
    testListName?: string | null;

    /**
     * 是否激活
     *
     * @type {number}
     * @memberof ProductEntry
     */
    active?: number | null;

    /**
     * 版本
     *
     * @type {number}
     * @memberof ProductEntry
     */
    version?: number | null;

    /**
     * 描述信息
     *
     * @type {string}
     * @memberof ProductEntry
     */
    description?: string | null;

    /**
     * 文件链接
     *
     * @type {string}
     * @memberof ProductEntry
     */
    fileLink?: string | null;

    /**
     * 等级模板
     *
     * @type {string}
     * @memberof ProductEntry
     */
    grade?: string | null;
}
