/* tslint:disable */
/* eslint-disable */
/**
 * 通用接口
 * 通用接口，针对权限、通用缓存、调度中心
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 用户配置表
 *
 * @export
 * @interface SysUserConfigEntry
 */
export interface SysUserConfigEntry {

    /**
     * @type {string}
     * @memberof SysUserConfigEntry
     */
    createUser?: string | null;

    /**
     * @type {Date}
     * @memberof SysUserConfigEntry
     */
    createTime?: Date | null;

    /**
     * @type {string}
     * @memberof SysUserConfigEntry
     */
    changeUser?: string | null;

    /**
     * @type {Date}
     * @memberof SysUserConfigEntry
     */
    changeTime?: Date | null;

    /**
     * 0为未删除，1为已删除
     *
     * @type {string}
     * @memberof SysUserConfigEntry
     */
    deleted?: string | null;

    /**
     * 数据权限
     *
     * @type {string}
     * @memberof SysUserConfigEntry
     */
    dataId?: string | null;

    /**
     * 主键
     *
     * @type {number}
     * @memberof SysUserConfigEntry
     */
    id?: number;

    /**
     * 用户工号，关联sys_user
     *
     * @type {string}
     * @memberof SysUserConfigEntry
     */
    userId?: string | null;

    /**
     * 配置类型
     *
     * @type {string}
     * @memberof SysUserConfigEntry
     */
    configType?: string | null;

    /**
     * 配置字段名
     *
     * @type {string}
     * @memberof SysUserConfigEntry
     */
    configField?: string | null;

    /**
     * 配置字段值
     *
     * @type {string}
     * @memberof SysUserConfigEntry
     */
    configValue?: string | null;

    /**
     * 状态
     *
     * @type {string}
     * @memberof SysUserConfigEntry
     */
    status?: string | null;
}
