/* tslint:disable */
/* eslint-disable */
/**
 * 通用接口
 * 通用接口，针对权限、通用缓存、调度中心
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 模板分项实体类
 *
 * @export
 * @interface TemplateItemEntry
 */
export interface TemplateItemEntry {

    /**
     * @type {string}
     * @memberof TemplateItemEntry
     */
    createUser?: string | null;

    /**
     * @type {Date}
     * @memberof TemplateItemEntry
     */
    createTime?: Date | null;

    /**
     * @type {string}
     * @memberof TemplateItemEntry
     */
    changeUser?: string | null;

    /**
     * @type {Date}
     * @memberof TemplateItemEntry
     */
    changeTime?: Date | null;

    /**
     * 0为未删除，1为已删除
     *
     * @type {string}
     * @memberof TemplateItemEntry
     */
    deleted?: string | null;

    /**
     * 数据权限
     *
     * @type {string}
     * @memberof TemplateItemEntry
     */
    dataId?: string | null;

    /**
     * 主键
     *
     * @type {number}
     * @memberof TemplateItemEntry
     */
    id?: number;

    /**
     * 模板ID
     *
     * @type {string}
     * @memberof TemplateItemEntry
     */
    templateId?: string | null;

    /**
     * 模板名称
     *
     * @type {string}
     * @memberof TemplateItemEntry
     */
    templateName?: string | null;

    /**
     * 配置字段名
     *
     * @type {string}
     * @memberof TemplateItemEntry
     */
    templateField?: string | null;

    /**
     * 字段类型
     *
     * @type {string}
     * @memberof TemplateItemEntry
     */
    fieleType?: string | null;

    /**
     * 默认值
     *
     * @type {string}
     * @memberof TemplateItemEntry
     */
    defaultValue?: string | null;

    /**
     * 公式型代码
     *
     * @type {string}
     * @memberof TemplateItemEntry
     */
    sourceCode?: string | null;

    /**
     * 列表型的列表名称
     *
     * @type {string}
     * @memberof TemplateItemEntry
     */
    listName?: string | null;

    /**
     * 列表型取值字段
     *
     * @type {string}
     * @memberof TemplateItemEntry
     */
    listField?: string | null;

    /**
     * 状态
     *
     * @type {string}
     * @memberof TemplateItemEntry
     */
    status?: string | null;
}
