/* tslint:disable */
/* eslint-disable */
/**
 * 通用接口
 * 通用接口，针对权限、通用缓存、调度中心
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 用户-岗位对应实体类
 *
 * @export
 * @interface UserPostEntry
 */
export interface UserPostEntry {

    /**
     * @type {number}
     * @memberof UserPostEntry
     */
    id?: number;

    /**
     * @type {string}
     * @memberof UserPostEntry
     */
    userId?: string | null;

    /**
     * @type {string}
     * @memberof UserPostEntry
     */
    userName?: string | null;

    /**
     * @type {string}
     * @memberof UserPostEntry
     */
    postId?: string | null;

    /**
     * @type {string}
     * @memberof UserPostEntry
     */
    postName?: string | null;
}
