/* tslint:disable */
/* eslint-disable */
/**
 * 通用接口
 * 通用接口，针对权限、通用缓存、调度中心
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
export * from './apis/analysis-api';
export * from './apis/configcenter-api';
export * from './apis/list-api';
export * from './apis/post-api';
export * from './apis/processunit-api';
export * from './apis/product-api';
export * from './apis/sample-api';
export * from './apis/sysauth-api';
export * from './apis/sysdynamicsub-api';
export * from './apis/sysgroup-api';
export * from './apis/sysrole-api';
export * from './apis/system-api';
export * from './apis/sysworkshop-api';
export * from './apis/test-api';
export * from './apis/testlist-api';

